Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

   config.vm.network "private_network", ip: "192.168.205.100"
   config.vm.hostname = "dockercoins"
   config.vm.define "dockercoins"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end

   config.vm.provision "shell", inline: <<-SHELL
     sudo systemctl disable systemd-resolved
     sudo rm -rf /etc/run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
     sudo echo "nameserver  8.8.8.8" > /etc/resolv.conf
     sudo apt-get update
     sudo apt-get install -y build-essential wget curl vim python ruby nodejs redis-server python-requests python-flask python-redis node-express node-redis python3-pip
     sudo pip3 install redis 
     sudo gem install sinatra 
     sudo gem install thin
   SHELL
end
